# -*- coding: utf-8 -*-
"""DATA  ANANLYSING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-ZDy_8NzZQvl0O15t8gczYc40uw5lFZ
"""

import pandas as pd
data=pd.read_csv('/content/weight-height.csv')
display(data)

"""in here the dataset csv file show shows how that we can read  for that we use the pd.read_csv() fungtion"""

data.head()

""" given dataset we are taken first 5 values . its
already the defalted value is 5 . we can give more values then shows how many values have


"""

data.tail()

"""given dataset are taken last 5 values . its already the defaulted value is 5 . we can give more values then shows how many values have"""

data.info()

""" in here we can clearly see that dataset .info updates flot type
digit type int type info .in here geving these kind of information
"""

data.isnull()

""" here we can seeing how many null values in these dataset
in here no null vales is here
"""

data.duplicated()

"""here we can see the dataset duplicated values and in these dataset are no duplicate value"""

data.drop_duplicates()

"""in here these function shows how to remove the duplicated values"""

data.describe()

"""in here the data described in that standered deviation,meanvalues,count,and some persentages 25%,50%,75%, and max values

these are some fungtions to clearly discribe the data features and then we can easily analysis the dataset
describe ,info, nullvales,head and tail these are the basic fungtions forananlysing the dataset
"""

